# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('user_date', models.DateField()),
                ('user_time', models.TimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
    ]
