# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Single User'), (2, 'Admin')]),
        ),
    ]
