# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170120_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_login',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
