# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
